first/urls.py
from . import views
from django.urls import path, include

app_name='first'

urlpatterns = [
    path('', views.index, name='index'),
    path('students', views.students, name='students'),
    path('students/<int:id>', views.students_detail, name='students_detail'),
    path('students/add', views.students_add, name='students_add'),
    path('students/del', views.students_del, name='students_del'),
    path('students/modify/<int:id>', views.students_modify, name='students_modify'),
    path('scores', views.scores, name='scores'), 
    path('scores/add', views.scores_add, name='scores_add'),
    path('scores/del', views.scores_del, name='scores_del'),
    path('makecookie/<name>', views.make_cookie, name='make_cookie')
]

newproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('first/', include('first.urls')),
    path('admin/', admin.site.urls),
    path('second/', include('second.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

second/urls.py
from . import views
from django.urls import path, include

app_name='second'
urlpatterns = [
    path('', views.index, name='index'),
    path('favourite', views.favourites, name='favourites'),
    path('favourite/<int:idn>', views.favourites_detail, name='favourites_detail'),
    path('favourite/register', views.favourites_add, name='favourites_add'),
    path('favourite/modify/<int:idn>', views.favourites_modify, name='favourites_modify'),
    path('favourite/delete', views.favourites_delete, name='favourites_delete'),
    path('favourite/quick', views.favourites_quick, name='favourites_quick'), # get 방식으로 삭제하는 옵션 추가
    path('todo', views.todo, name='todos'),
    path('todo/<int:ids>', views.todo_detail, name='todo_detail'),
    path('todo/register', views.todo_add, name='todo_add'),
    path('todo/modify/<int:ids>', views.todo_modify, name='todo_modify'),
    path('todo/delete', views.todo_delete, name='todo_delete'),
    path('todo/quick', views.todo_quick, name='todo_quick'),
    path('todo/shift', views.todo_shift, name='todo_shift'),
    path('signup', views.signup, name='signup'),
    path('login', views.signin, name='login'),
    path('changeuserinfo', views.changeuserinfo, name='changeuserinfo'),
    path('logout', views.signout, name='logout'),
]

second/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
# 기존 유저테이블이 아닌 새로 만들어야 한다.
class User(AbstractUser): #사용자 정보 추가 (사용자 처리는 전담.)
    phone_number=models.CharField(max_length=20, blank=True)
    profile = models.ImageField(verbose_name='user\'s profile image', null=True, blank=True, upload_to='second/profiles/')

class FavouriteGroup(models.Model):
    seq = models.AutoField(primary_key = True)
    name = models.CharField(max_length=50)
    reg_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Favourite(models.Model):
    seq = models.AutoField(primary_key = True)
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    memo = models.TextField()
    reg_date = models.DateField(auto_now_add = True)
    user = models.CharField(max_length=30, default='AnonymousUser')
    # reg_user = models.ForeignKey(User, on_delete = models.CASCADE)
    group = models.ForeignKey(FavouriteGroup, on_delete = models.CASCADE)
    
class newprojGroup(models.Model):
    seq = models.AutoField(primary_key = True)
    name = models.CharField(max_length=50)
    reg_date = models.DateField(auto_now_add=True)
    del_yn = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class newproj(models.Model):
    seq = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    status = models.CharField(max_length=10)
    reg_date = models.DateField(auto_now_add=False)
    end_date = models.DateField()
    del_yn = models.BooleanField(default=False)
    group = models.ForeignKey(newprojGroup, on_delete=models.CASCADE) 

class TodoGroup(models.Model):
    seq = models.AutoField(primary_key = True)
    name = models.CharField(max_length=50)
    reg_date = models.DateField(auto_now_add=True)
    del_yn = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Todo(models.Model):
    STATUS_LIST=[
        ('Pending', '할일'),
        ('Inprogress', '진행중'),
        ('End', '완료'), 
    ]
    seq = models.AutoField(primary_key = True)
    name = models.CharField(max_length=50)
    status = models.CharField(max_length=10, choices=STATUS_LIST)
    reg_date = models.DateField(auto_now_add = True)
    end_date = models.DateField()
    del_yn = models.BooleanField(default=False)
    user = models.CharField(max_length=30, default='AnonymousUser')
    # reg_user = models.ForeignKey(User, on_delete = models.CASCADE)
    group = models.ForeignKey(TodoGroup, on_delete = models.CASCADE)

todo/models.py
from django.db import models

# Create your models here.

second/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm #회원가입 창
from django.forms.widgets import HiddenInput
from .models import Favourite, FavouriteGroup, Todo, TodoGroup, User
import re

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = '비밀번호'
        self.fields['password2'].label = '비밀번호확인'
        self.fields['username'].help_text = '필수입력. 30자 이내. 영숫자 및 @/./+/-/_만 허용'
        self.fields['password1'].help_text = '영숫자 혼용, 최소 8자리 이상'
        self.fields['password2'].help_text = ''
    # * -> 리스트 - 튜플 차이
    # ** -> 딕셔너리 - x=y형태로 딕셔너리
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'phone_number', 'profile']
        labels ={
            'username':'아이디',
            'email':'이메일',
            'phone_number':'휴대전화 번호',
            'profile':'프로필'
        }

class ChangeInfoForm(SignupForm): # id 등 중요한 정보는 수정 못하게...
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = '비밀번호'
        self.fields['password2'].label = '비밀번호확인'
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        
    class Meta(SignupForm.Meta):
        model = User
        fields = ['username','email', 'phone_number', 'profile', 'password1', 'password2']
        labels = {
            'email':'이메일',
            'phone_number':'휴대전화 번호',
            'profile':'프로필'
        }
        widgets = {'username':forms.HiddenInput(),
        'password1':forms.HiddenInput(),
        'password2':forms.HiddenInput()
        }



class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        pass

    class Meta(UserCreationForm.Meta):
        model=User
        fields = ['username', 'password']
        labels = {
            'username':'아이디',
            'password':'비밀번호'
        }


class FavouriteModelForms(forms.ModelForm):
    class Meta: #반드시 입력해야 한다!
        model = Favourite
        fields = ['name', 'url', 'memo', 'group']#전부다 입력
        labels = {
            'name':'명칭', 'url': 'URL', 'memo':'메모', 'group':'그룹'
        }

class TodoModelForms(forms.ModelForm):
    class Meta: #반드시 입력해야 한다!
        model = Todo
        fields = ['name', 'status', 'end_date', 'group']
        labels = {
            'name':'명칭', 'status':'상태', 'end_date':'종료일', 'group':'그룹'
        }

second/views.py
from django.shortcuts import render, redirect
from .models import Favourite, FavouriteGroup, Todo, TodoGroup, User
from .forms import FavouriteModelForms, TodoModelForms, SignupForm, LoginForm, ChangeInfoForm
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'second/layout.html')

@login_required
def favourites(request):
    if request.method == 'GET':
        favourites = Favourite.objects.filter(user=request.user.username)

        return render(request, 'second/favourites.html', {
            'favourites': favourites
        })

@login_required
def favourites_detail(request, idn):
    favourite = Favourite.objects.get(pk=idn)
    delid = f'del-favourite-{favourite.seq}'
    favourites = Favourite.objects.filter(user=request.user.username)
    if favourite in favourites:
        return render(request, 'second/favourite_detail.html', {
            'favourite': favourite,
            'delid': delid,
            'idn' : idn
        })
    else:
        return render(request, 'second/noauth.html', {
            'action':'Favourite',
            'action_kr':'즐겨찾기가'
        })

@login_required
def favourites_add(request):
    form = FavouriteModelForms()
    if request.method == 'GET': #get 메소드로 얻을 때는 강제
        return render(request, 'second/add.html', {
            'form':form, 
            'action':'등록',
            'do_action':'Add Favourite'
        })

    elif request.method == 'POST':
        form = FavouriteModelForms(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.POST['user']
            post.save()
            return redirect('second:favourites')
        else:
            return render(request, 'second/add.html', {
                'form':form,
                'action':'등록',
                'do_action':'Add Favourite'
            })

@login_required
def favourites_modify(request, idn):
    favourite = Favourite.objects.get(seq=idn)
    
    if request.method == 'GET': #get 메소드로 얻을 때는 강제
        form = FavouriteModelForms(instance=favourite)
        favourites = Favourite.objects.filter(user=request.user.username)
        if favourite in favourites:
            return render(request, 'second/add.html', {
                'form':form,
                'action':'수정',
                'do_action':'Modify Favourite',
            })
        else:
            return render(request, 'second/noauth.html', {
            'action':'Favourite',
            'action_kr':'즐겨찾기가'
            })


    elif request.method == 'POST':
        form = FavouriteModelForms(request.POST, instance=favourite)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.POST['user']
            post.save()
            return redirect('second:favourites')
        else:
            return render(request, 'second/add.html', {
                'form':form,
                'action':'수정',
                'do_action':'Modify Favourite',
            })

@login_required
def favourites_delete(request):
    if request.method == 'GET':
        return redirect('second:favourites')
    
    elif request.method == 'POST':
        delpk = request.POST['del']
        item = Favourite.objects.get(pk=delpk)
        item.delete()
        return redirect('second:favourites')

def favourites_quick(request):
    if request.method == 'GET' and request.GET.get('del'):
        delpk = request.GET['del']
        item = Favourite.objects.get(pk=delpk)
        item.delete()
        favourites = Favourite.objects.filter(user=request.user.username)
        return render(request, 'second/favourites.html', {
            'favourites':favourites
        })
        
        
@login_required
def todo(request):

    todos_pending = Todo.objects.filter(status='Pending', user=request.user.username)
    todos_inprogress = Todo.objects.filter(status='Inprogress', user=request.user.username)
    todos_end = Todo.objects.filter( status='End', user=request.user.username)

    return render(request, 'second/todos.html', {
        'todos_pending' : todos_pending,
        'todos_inprogress' : todos_inprogress,
        'todos_end' : todos_end
    })

@login_required
def todo_detail(request, ids):
    todo = Todo.objects.get(pk=ids)
    delid = f'del-todo-{todo.seq}'
    todos = Todo.objects.filter(user=request.user.username)
    if todo in todos:
        return render(request, 'second/todo_detail.html', {
            'todo': todo,
            'delid': delid,
            'idn': ids
        })
    else:
        return render(request, 'second/noauth.html', {
            'action': 'Todo',
            'action_kr': '할일이'
        })
    
@login_required
def todo_add(request):
    form = TodoModelForms()
    if request.method == 'GET': #get 메소드로 얻을 때는 강제
        return render(request, 'second/add.html', {
            'form':form,
            'action':'등록',
            'do_action':'Add Todo',
        })

    elif request.method == 'POST':
        form = TodoModelForms(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.POST['user']
            post.save()
            return redirect('second:todos')
        else:
            return render(request, 'second/add.html', {
                'form':form,
                'action':'등록',
                'do_action':'Add Todo',
            })

@login_required
def todo_modify(request, ids):
    todo = Todo.objects.get(seq=ids)
    
    if request.method == 'GET': #get 메소드로 얻을 때는 강제
        form = TodoModelForms(instance=todo)
        todos = Todo.objects.filter(user=request.user.username)
        if todo in todos:
            return render(request, 'second/add.html', {
                'form':form,
                'action':'수정',
                'do_action':'Modify Todo',
            })
        else:
            return render(request, 'second/noauth.html', {
            'action': 'Todo',
            'action_kr': '할일이'
        })


    elif request.method == 'POST':
        form = TodoModelForms(request.POST, instance=todo)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.POST['user']
            post.save()
            return redirect('second:todos'),
        else:
            return render(request, 'second/add.html', {
                'form':form,
                'action':'수정',
                'do_action':'Modify Todo',
            })

@login_required
def todo_delete(request):
    if request.method == 'GET':
        return redirect('second:todos')
    
    elif request.method == 'POST':
        delpk = request.POST['del']
        item = Todo.objects.get(pk=delpk)
        item.delete()
        return redirect('second:todos')

@login_required
def todo_quick(request):
    if request.method == 'GET' and request.GET.get('del'):
        delpk = request.GET['del']
        item = Todo.objects.get(pk=delpk)
        item.delete()
        todos = Todo.objects.filter(user=request.user.username)
        return render(request, 'second/todos.html', {
            'todos':todos
        })
        
        
@login_required
def todo_shift(request):
    if request.method == 'GET' and request.GET.get('status') and request.GET.get('seq'):
        seq = request.GET['seq']
        status = request.GET['status']
        item = Todo.objects.get(pk=seq)
        item.status = status
        item.save()
        todos = Todo.objects.filter(user=request.user.username)
        return render(request, 'second/todos.html', {
            'todos':todos
        })

def signup(request):
    if request.method == 'GET':
        form=SignupForm()
        return render(request, "second/signup.html", {
            'form':form,
            'action':'회원가입'
        })
    elif request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            signed_user = form.save()
            return redirect('second:index')
        else:
            return render(request, 'second/signup.html', {
                'form':form,
                'action' : '회원가입'
            })

def signin(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, "second/signup.html", {
            'form':form,
            'action':'로그인'
        })
    
    elif request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('second:index')
        else:
            return render(request, "second/signup.html", {
            'form':form,
            'action':'로그인'
        })

@login_required
def changeuserinfo(request):
    userinfo = User.objects.get(username=request.user.username)
    if request.method == 'GET':
        form=ChangeInfoForm(instance=userinfo)
        return render(request, "second/signup.html", {
            'form':form,
            'action':'회원정보수정'
        })
    elif request.method == 'POST':
        form = ChangeInfoForm(request.POST, request.FILES, instance=userinfo)
        if form.is_valid():
            signed_user = form.save()
            update_session_auth_hash(request, signed_user)
            return render(request, 'second/layout.html', {})
        else:
            return render(request, 'second/signup.html', {
                'form':form,
                'action' : '회원정보수정'
            })        

@login_required
def signout(request):
    if request.method == 'GET':
        logout(request)
        return redirect('second:index')

todo/views.py
from django.shortcuts import render

# Create your views here.

second/templates/second/favourite_detail.html
{% extends 'second/detail_pages.html' %}

{% block title %}
Favourite {{ favourite.name }}
{% endblock %}

{% block content_title %}
{{ favourite.name }}
{% endblock %}

{% block content_modify_url %}
{% url 'second:favourites_modify' favourite.seq %}
{% endblock %}

{% block content_delete_url %}
{% url 'second:favourites_delete' %}
{% endblock %}

{% block content_detail %}
            <div class='item-box'>
                <table class='item-box-table'>
                    <tr>
                        <td>순번</td>
                        <td> {{ favourite.seq }}</td>
                    </tr>
                    <tr>
                        <td>명칭</td>
                        <td>{{ favourite.name }}</td>
                    </tr>
                    <tr>
                        <td>URL</td>
                        <td>{{ favourite.url }}</td>
                    </tr>
                    <tr>
                        <td>메모</td>
                        <td>{{ favourite.memo }}</td>
                    </tr>
                    <tr>
                        <td>등록일</td>
                        <td>{{ favourite.reg_date }}</td>
                    </tr>
                    <tr>
                        <td>그룹</td>
                        <td>{{ favourite.group }}</td>
                    </tr>
                </table>
            </div>
    </div>
{% endblock %}

second/templates/second/favourites.html
{% extends 'second/layout.html' %}

{% block title %}
Favourites
{% endblock %}
{%block newcss %}
<style>
    /* item-box related */
    .item-box-image{
        float:right;
    }
    .sublist{
        display:none;
    }
    .sublist ul{
        list-style-type:none;
        padding:0;
        margin:0;
    }
    .item-box-image:hover .sublist{
        display:block;
    }
    .item-box-image:hover .sublist li{
        background-color:white;
        width:5em;
        position:absolute;
        right:0em;
        border: 1px solid black;
        z-index:1;
    }
</style>
{% endblock %}

{% block content %}
{% load static %}
<div id="content-block">
<h2>즐겨찾기 <span class='right-content'><a href="{% url 'second:favourites_add' %}"><img src="{% static 'second/icon_add.png' %}"/></a></span></h2>
<hr>
<div class='item-box-enclose'>
        {% for favourite in favourites %}
        <!-- 반복 -->
        <div class='item-box' id='item-box-{{ favourite.seq }}'>
            <span class='headline-small'><a href="{% url 'second:favourites_detail' favourite.seq %}">{{ favourite.name }}</a></span>
            <div class='right-content'>
            {{ favourite.reg_date|date:"Y-m-d" }} &nbsp;&nbsp;
            {{ favourite.group }}
            <div class='item-box-image'>
            <img src="{% static 'second/icon_more.png' %}"  id= 'item-box-{{favourite.seq}}-image' style='height:1em;'/>
            <div id ="item-list-{{favourite.seq}}" class="sublist"><ul><li id="del-{{favourite.seq}}-from-list">삭제</li></ul></div>
            </div></div>
        </div>
        <script>
            document.getElementById('del-{{favourite.seq}}-from-list').onclick = () => {
                let val = "{{favourite.seq}}";
                del_process(val);
            }            
        </script>
        {% endfor %}
</div>
</div>
<script>
del_process = (_val) =>{
    fetch("{% url 'second:favourites_quick'  %}"+'?'+ new URLSearchParams({'del':_val })).then(() => {
                    idbox = document.querySelector('#item-box-'+_val);
                    idbox.remove(); //시각적으로 조작
                }
                );
};
</script>

{% endblock %}

second/templates/second/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}
        {% endblock %}</title>
{% block newcss %}
{% endblock %}
{% load static %}
    
    <style>
    @import url("{% static 'second/style.css' %}");
    </style>
    </head>

    <body>
        <div id="list">
        <div class="headline">Dogo&amp;Favorite</div>
        <ul>
        <li><img src="{% static 'second/icon_home.png' %}"/> <a href="{% url 'second:index' %}">Home</a> </li>
        <li><img src="{% static 'second/icon_favorite.png' %}"/> <a href="{% url 'second:favourites' %}">Favourite</a> </li>
        <li><img src="{% static 'second/icon_todo.png' %}"/> <a href="{% url 'second:todos' %}">Todo</a></li>
    </ul>
    </div>
    <div id="contents">
        {% if request.user.is_authenticated == False %}
        <div class='block-upper'><a href="{% url 'second:login' %}">로그인</a> &nbsp;
            <a href="{% url 'second:signup' %}">회원가입</a></div>
        {% else %}

        <div class='block-upper'>
        {% if request.user.profile %}
        <img style="border-radius:50%%;width:1.3em;height:1.3em;" src="{{request.user.profile.url}}"/>
        {% endif %}
        {{request.user}} &nbsp;
        <a href="{% url 'second:changeuserinfo' %}">회원정보수정</a> &nbsp; 
        <a href="{% url 'second:logout' %}">로그아웃</a></div>
        
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    </body>
</html>

second/templates/second/todos.html
{% extends 'second/layout.html' %}

{% block title %}
todos_end
{% endblock %}
{% block newcss %}
<style>

</style>
{% endblock %}

{% block content %}
{% load static %}
<div id="content-block">
<script>val_list =[];</script>
<h2>내가할일<span class='right-content'><a href="{% url 'second:todo_add' %}"><img src="{% static 'second/icon_add.png' %}"/></a></span></h2>
<hr>
<div class='item-box-enclose-3'>
    <h3 class='center'>대기중</h3>
        {% for todo in todos_pending %}
        <!-- todo pending -->
        <div class='item-box' id='item-box-{{ todo.seq }}'>
            <span class='headline-small'><a href="{% url 'second:todo_detail' todo.seq %}">{{ todo.name }}</a></span>
            <div class='right-content'>
            {{ todo.end_date|date:"Y-m-d" }} 
            {{ todo.group }}
                <div class='item-box-image'> 
                    <img src="{% static 'second/icon_more.png' %}"  id= 'item-box-{{todo.seq}}-image' style='height:1em;'/>
                    <div id ="item-list-{{todo.seq}}" class="sublist">
                        <ul>
                            <li id="del-{{todo.seq}}-from-list">삭제</li>
                            <li id="shift-{{todo.seq}}-to-pending">대기중</li>
                            <li id="shift-{{todo.seq}}-to-inprogress">진행중</li>
                            <li id="shift-{{todo.seq}}-to-end">완료</li>
                        </ul>
                    </div>
                </div> 
           </div>
        </div>
        <script>
        var val = "{{todo.seq}}"
        val_list.push(val);
            document.getElementById('del-{{todo.seq}}-from-list').onclick = () =>{ 
                let val = "{{todo.seq}}";
                del_process(val);
            };
            document.getElementById('shift-{{todo.seq}}-to-pending').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 0);
            };
            document.getElementById('shift-{{todo.seq}}-to-inprogress').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 1);
            };
            document.getElementById('shift-{{todo.seq}}-to-end').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 2);
            };
        </script>
        {% endfor %}
</div>
<div class='item-box-enclose-3'>
    <h3 class='center'>진행중</h3>
    {% for todo in todos_inprogress %}
        <!-- todo_inprogress -->
        <div class='item-box' id='item-box-{{ todo.seq }}'>
            <span class='headline-small'><a href="{% url 'second:todo_detail' todo.seq %}">{{ todo.name }}</a></span>
            <div class='right-content'>
            {{ todo.end_date|date:"Y-m-d" }} 
            {{ todo.group }}
                <div class='item-box-image'>
                    <img src="{% static 'second/icon_more.png' %}"  id= 'item-box-{{todo.seq}}-image' style='height:1em;'/>
                    <div id ="item-list-{{todo.seq}}" class="sublist">
                        <ul>
                            <li id="del-{{todo.seq}}-from-list">삭제</li>
                            <li id="shift-{{todo.seq}}-to-pending">대기중</li>
                            <li id="shift-{{todo.seq}}-to-inprogress">진행중</li>
                            <li id="shift-{{todo.seq}}-to-end">완료</li>
                        </ul>
                    </div>
                </div>
            </div>
    </div>
        <script>
        var val = "{{todo.seq}}"
        val_list.push(val);
            document.getElementById('del-{{todo.seq}}-from-list').onclick = () =>{ 
                let val = "{{todo.seq}}";
                del_process(val);
            };
            document.getElementById('shift-{{todo.seq}}-to-pending').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 0);
            };
            document.getElementById('shift-{{todo.seq}}-to-inprogress').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 1);
            };
            document.getElementById('shift-{{todo.seq}}-to-end').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 2);
            };
        </script>
    {% endfor %}
</div>
<div class='item-box-enclose-3'>
    <h3 class='center'>완료</h3>
    {% for todo in todos_end %}
        <!--todo_end -->
        <div class='item-box' id='item-box-{{ todo.seq }}'>
            <span class='headline-small'><a href="{% url 'second:todo_detail' todo.seq %}">{{ todo.name }}</a></span>
            <div class='right-content'>
            {{ todo.end_date|date:"Y-m-d" }} 
            {{ todo.group }}
                <div class='item-box-image'>
                    <img src="{% static 'second/icon_more.png' %}"  id= 'item-box-{{todo.seq}}-image' style='height:1em;'/>
                    <div id ="item-list-{{todo.seq}}" class="sublist">
                        <ul>
                            <li id="del-{{todo.seq}}-from-list">삭제</li>
                            <li id="shift-{{todo.seq}}-to-pending">대기중</li>
                            <li id="shift-{{todo.seq}}-to-inprogress">진행중</li>
                            <li id="shift-{{todo.seq}}-to-end">완료</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <script>
        var val = "{{todo.seq}}"
        val_list.push(val);
            document.getElementById('del-{{todo.seq}}-from-list').onclick = () =>{ 
                let val = "{{todo.seq}}";
                del_process(val);
            };
            document.getElementById('shift-{{todo.seq}}-to-pending').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 0);
            };
            document.getElementById('shift-{{todo.seq}}-to-inprogress').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 1);
            };
            document.getElementById('shift-{{todo.seq}}-to-end').onclick = () =>{ 
               let val = "{{todo.seq}}";
               shift_process(val, 2);
            };
        </script>
    {% endfor %}
</div>
</div>
<script>
del_process = (_val) =>{
    fetch("{% url 'second:todo_quick'  %}"+'?'+ new URLSearchParams({'del':_val })).then(() => {
                    idbox = document.querySelector('#item-box-'+_val);
                    idbox.remove(); //시각적으로 조작
                }
                );
};
function hide_list(_val){ //메뉴 숨기기
    box_list = document.querySelectorAll('.item-box-enclose-3');
    item_list = document.querySelector('#item-list-'+_val);
    _num=-1;
    for (let j=0;j<3;j++){
        if (box_list[j].querySelector('#item-list-'+_val) === item_list){ // 현재 item_list 위치 찾기
        _num=j; 
        break;
        }
    }
    for (let i=0; i<4;i++){
    if (i == _num+1){ //num일 때만 숨기기.
        item_list.querySelectorAll('li')[i].style.display='none';
    }
    else{
        item_list.querySelectorAll('li')[i].style.display='block';
    }
    }
};
shift_process = (_val, _num) =>{ //상자 위치 이동 함수
    status_list = ['Pending', 'Inprogress', 'End'];
    idbox = document.querySelector('#item-box-'+_val);
    box_list = document.querySelectorAll('.item-box-enclose-3');
    fetch("{% url 'second:todo_shift'  %}"+'?'+ new URLSearchParams({'seq':_val, 'status':status_list[_num]})).then(() =>{
    box_list[_num].appendChild(idbox);
    hide_list(_val);}
    );
};
for (_val of val_list){
    hide_list(_val);
}

</script>
{% endblock %}