first/urls.py
from . import views
from django.urls import path, include

app_name='first'

urlpatterns = [
    path('', views.index, name='index'),
    path('students', views.students, name='students'),
    path('students/<int:id>', views.students_detail, name='students_detail'),
    path('students/add', views.students_add, name='students_add'),
    path('students/del', views.students_del, name='students_del'),
    path('students/modify/<int:id>', views.students_modify, name='students_modify'),
    path('scores', views.scores, name='scores'), 
    path('scores/add', views.scores_add, name='scores_add'),
    path('scores/del', views.scores_del, name='scores_del'),
    path('makecookie/<name>', views.make_cookie, name='make_cookie')
]

newproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('first/', include('first.urls')),
    path('admin/', admin.site.urls),
    path('second/', include('second.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/models.py
from django.db import models
from django import forms
from uuid import uuid4 #random id 생성
import os

# Create your models here.
def upload_to(instance, filename):
    path = 'file/'
    uuid_name = uuid4().hex
    #확장자 추출
    extension = os.path.splitext(filename)[-1].lower()
    #filename.split('.')[-1]
    return path + uuid_name + extension+'/'

class Students(models.Model):
    name=models.CharField(max_length=10)
    address = models.CharField(max_length=50)
    email = models.CharField(max_length=30)
    file1 = models.FileField(null=True, blank=True, upload_to='')
    file2 = models.FileField(null=True, blank=True, upload_to=upload_to)
    image1 = models.ImageField(null=True, blank=True, upload_to='images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='%Y/%m/%d')


class Scores(models.Model):
    name = models.CharField(max_length=10)
    math = models.IntegerField()
    english = models.IntegerField()
    science = models.IntegerField()
    

first/forms.py
from django import forms
from .models import Students
import re

def check_address(value): #validator - 리스트 형태로 여러개 입력 가능.
    if len(value)<3 or bool(re.search('\s', value))==False:
        raise forms.ValidationError('적절한 주소 형태로 입력해주세요!')
def check_email(value): 
    if bool(re.match('[A-Za-z0-9_+\.,]+@[a-z\.]+',value))==False:
        raise forms.ValidationError('적절한 이메일 형식이 아닙니다!')

class StudentForms(forms.Form): #Django Form 
    name = forms.CharField(label='이름', max_length=10)
    address = forms.CharField(label='주소', validators=[check_address, ])
    email = forms.CharField(widget=forms.Textarea, validators=[check_email, ])

class StudentModelForms(forms.ModelForm):
    class Meta: #반드시 입력해야 한다!
        model = Students
        fields = '__all__' #전부다 입력

first/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest, Http404
from .models import Students, Scores
from .forms import StudentForms, StudentModelForms # import 하기

# Create your views here.
def index(request):
    # print(request.COOKIES)
    # request.session['userid'] = 'yohan'
    # del request.session['userid']  #세션 지울 때
    # request.session['count'] = '0' 
    return render(request, 'first/index.html')

def students(request):
    if request.method == 'GET':
        if request.GET.get('start') and request.GET.get('end'):
            start = int(request.GET['start'])
            end = int(request.GET['end'])
            students = Students.objects.filter(pk__range=(start, end))

        else:
            students = Students.objects.all()
        
        return render(request, 'first/students.html', {
            'text':'안녕하세요',
            'students': students
        })


def students_detail(request, id):
    print('id:', id)
    students = Students.objects.filter(pk=id)
    """
        SELECT * FROM students
        where pk=id 
    """
    return render(request, 'first/students.html', {
        'text':'안녕하세요',
        'students': students
    })

def students_add(request):
    #form = StudentForms() #폼 객체 생성
    form = StudentModelForms()
    if request.method == 'GET': #get 메소드로 얻을 때는 강제
        
        return render(request, 'first/students_add.html', {
            'form':form
        })

    elif request.method == 'POST':
        form = StudentModelForms(request.POST, request.FILES) #파일 업로드할 때는 반드시 FILES도 입력!
        if form.is_valid():
            post = form.save()
            return redirect('first:students')
        else:
            return render(request, 'first/students_add.html', {
                'form':form
            })

def students_modify(request,id):
    try:
        student = Students.objects.get(pk=id)
    except:
        raise Http404("404")

    if request.method=='GET':
        form = StudentModelForms(instance=student) #instance값이 나옴.
        return render(request,'first/students_add.html',{
            'form':form})

    elif request.method=='POST':
        form = StudentModelForms(request.POST,instance=student)
        if form.is_valid():
            student=form.save()
            return render(request,'first/students_add.html',{
                'form':form})

def students_del(request):
    if request.method == 'GET':
        return redirect('first:students')
    
    elif request.method == 'POST':
        delpk = request.POST['del']
        item = Students.objects.get(pk=delpk)
        delname = item.name
        item.delete()
        return render(request, 'first/students_del.html', {
            'name':delname
        } )

def scores(request):
    if request.method == 'GET':
        scores = Scores.objects.all()
        return render(request, 'first/scores.html', {
            'scores' : scores
        })

def scores_add(request):
    if request.method == 'GET':
        return render(request, 'first/scores_add.html')

    elif request.method == 'POST':
        if request.POST['name'] != '':
            Scores.objects.create(name=request.POST['name'],
            math=request.POST['math'],
            english=request.POST['english'],
            science=request.POST['science'])
        else:
            pass
        
        return redirect('first:scores')


def scores_del(request):
    if request.method == 'GET':
        return redirect('first:scores')
    
    elif request.method == 'POST':
        delpk = request.POST['del']
        item = Scores.objects.get(pk=delpk)
        delname = item.name
        item.delete()
        return render(request, 'first/scores_del.html', {
            'name':delname
        } )

def make_cookie(request, name):
    response = HttpResponse()
    response.set_cookie('name', name)
    return response

def get_cookie(request):
    pass

first/templates/first/index.html
<h1>Hello World!</h1>
<!--
<h3> 쿠키명 :  {{request.COOKIES.name}} </h3>
<h3> 세션명(userid) : {{request.session.userid}}</h3>

<script>
//    document.cookie="name=test1"
//    console.log(document.cookie)
</script>
-->

first/templates/first/layout.html
<!DOCTYPE html>
<html>
    <head>
        {% block title %}
        {% endblock %}
    </head>

    <body>
        <a href="{% url 'first:students' %}">학생정보</a>
        <a href="{% url 'first:scores' %}">점수정보</a>
        {% block content %}
        {% endblock %}

    </body>
</html>

first/templates/first/scores.html
{% extends 'first/layout.html' %}

{% block title %}
<title>점수</title>
{% endblock %}

{% block content %}
<br/>
<button id="score_add">추가</button>
        <table>
        <tr>
            <th>이름</th>
            <th>수학</th>
            <th>과학</th>
            <th>영어</th>
            <th>삭제</th>
        </tr>
        {% for score in scores %}
        <!-- 반복 -->
        <tr>
        <td>{{ score.name }}</td>    
        <td>{{ score.math }}</td>
        <td>{{ score.science }}</td>
        <td>{{ score.english }}</td>
        <td> 
            <form action="{% url 'first:scores_del' %}" method="POST">
                {%csrf_token%}
                <input type='hidden' name="del"
                  value={{score.pk}} />
                <input type="submit" value="삭제"/></form> </td>
    </tr>
        {% endfor %}
    </table>
    <script>
        document.querySelector('#score_add').onclick = function(){
            location.href="{% url 'first:scores_add' %}";
        };
    </script>
{% endblock %}

first/templates/first/scores_add.html
<form action="{% url 'first:scores_add' %}" method="post">
    {%csrf_token%}
    <label for="name">이름</label> <input name="name" type="text"/> <br/>
    <label for="math">수학</label> <input name="math" type="text"/> <br/>
    <label for="english">영어</label> <input name="english" type="text"/><br/>
    <label for="science">과학</label> <input name="science" type="text"/><br/>
    <input type="submit" value="등록"/>
</form>

first/templates/first/scores_del.html
<!doctype html>
<html>
<head>
    <meta charset='utf-8'/>
</head>
<body>{{name}} 점수정보가 삭제됩니다. 
    <a href="{% url 'first:scores' %}">돌아가기</a>
</body>
</html>

first/templates/first/students.html
{% extends 'first/layout.html' %}

{% block title %}
<title>학생 정보</title>
<style>
    #form_del, #form_mod{
        display:inline;
    }
</style>
{% endblock %}

{% block content %}
<button id="student_add">추가</button>
        <h2>{{ text }}</h2>

        {% for student in students %}
        <!-- 반복 -->
        <div>
            {{ student.name }}
            {{ student.address }}
            {{ student.email }}
            {% if student.file1 %}
            <div>{{ student.file1 }}{{ student.file1.url }}</div>
            {% endif %}
            {% if student.file2 %}
            <div>{{ student.file2 }}{{ student.file2.url }}</div>
            {% endif %}
            {% if student.image1  %}
            <div>{{ student.image1 }}{{ student.image1.url }}</div>
            {% endif %}
            {% if student.image2 %}
            <div>{{ student.image2 }}{{ student.image2.url }}</div>
            {% endif %}
            <form id="form_mod" action="{% url 'first:students_modify' student.pk %}" method="POST">
                {%csrf_token%}
                <input type='hidden' name="name" value={{student.name}} />
                <input type='hidden' name="address" value={{student.address}} />
                <input type='hidden' name="email" value={{student.email}} />
                <input type="submit" value="수정"/></form>
            <form id="form_del" action="{% url 'first:students_del' %}" method="POST">
                {%csrf_token%}
                <input type='hidden' name="del" value={{student.pk}} />
                <input type="submit" value="삭제"/></form>
        </div>
        {% endfor %}
<script>
    document.querySelector('#student_add').onclick = function(){
        location.href="{% url 'first:students_add' %}";
    };
</script>
{% endblock %}

first/templates/first/students_add.html
<!--<form action="{% url 'first:students_add' %}" method="post">
    {% csrf_token %}
    이름 : <input name="name" type="text"/><br/>
    주소 : <input name="address" type="text"/><br/>
    이메일 : <input name="email" type="text"/><br/>
    <input type="submit" value="등록"/>
</form> -->
<form action='' method="post" enctype="multipart/form-data">
{% csrf_token %}
<table>
    {{form.as_table}}
</table>
<input type="submit" value="등록"/>
</form>

first/templates/first/students_del.html
<!doctype html>
<html>
<head>
    <meta charset='utf-8'/>
</head>
<body>{{name}} 개인정보가 삭제됩니다. 
    <a href="{% url 'first:students' %}">돌아가기</a>
</body>
</html>